### ISSUE TITLE
'ps5bot' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mc130h** [rupeshdabbir/getme-ps5-bot#1]
Still getting this error after following your steps, any help?

**Comment by rupeshdabbir** [comment]
Follow the instructions now. You could run `yarn` and then use `yarn run ps5bot` to get the bot up and running!

After that you can use `yarn run ps5bot scrape` command to start the process.

If you encounter puppeteer issues, you can do `npm install -g puppeteer` (use sudo if you get permission errors)
