### ISSUE TITLE
yarn run ps5bot command failing in both Command Prompt and webstorm terminal

### ISSUE THREAD

**Issue by SalamiSandwich0** [rupeshdabbir/getme-ps5-bot#2]
I keep getting this error everytime I try to run your bot 
yarn run v1.22.10
$ ./bin/ps5bot
'.\bin\ps5bot' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rupeshdabbir** [comment]
Did you follow all the steps? 

Can you run "yarn" on the command line and then run yarn run ps5bot ?
